### ISSUE TITLE
[run_alignment_tool]  NoneType' object has no attribute '__getitem__

### ISSUE THREAD

**Issue by hoangcuongbk80** [RobotLocomotion/LabelFusion#26]
I run run_alignment_tool and get a error as shown in the screenshot:
![1](https://user-images.githubusercontent.com/10355081/42165668-0a631732-7e09-11e8-867f-d60b15fa3983.png)

**Comment by peteflorence** [comment]
Hi there, you need to do run_alignment_tool from inside of a log folder.
Your current path is LabelFusion/data. The path should be something like
LabelFusion/data/logs_test/2018-07-01-01/

Also prior to running the alignment tool you’ll need to have made the 3D
reconstruction. That is done with the run_prep command.

Does that help?

**Comment by hoangcuongbk80** [comment]
It works! Thank you so much!

**Comment by EthonDeep** [comment]
Hi  @peteflorence :
       i have the same question ,but it doesn't  works!
root@cd8330014561:~/labelfusion/data/logs_test/2018-09-21-01# run_alignment_tool 
Opening object alignment tool...
log folder: logs_test/2018-09-21-01
Traceback (most recent call last):
  File "/root/labelfusion/scripts/labelFusionApp.py", line 79, in <module>
    globalsDict=globals())
  File "/root/labelfusion/modules/labelfusion/setup.py", line 38, in setupLabelFusionDirector
    firstFrameToWorldTransform = utils.getFirstFrameToWorldTransform(filenames['transforms'])
TypeError: 'NoneType' object has no attribute '__getitem__'
Done.
root@cd8330014561:~/labelfusion/data/logs_test/2018-09-21-01#
