### ISSUE TITLE
How to visualize color object model instead of gray one?

### ISSUE THREAD

**Issue by hoangcuongbk80** [RobotLocomotion/LabelFusion#51]
Hi,

Could I display object model in the step "Align each object and crop point clouds" with color, my mesh original model has color. but it become gray when load it for alignment.
Gray:
![gray](https://user-images.githubusercontent.com/10355081/57714652-40af6b00-7675-11e9-907d-43d64260326e.png)

color:
![color](https://user-images.githubusercontent.com/10355081/57714904-d21edd00-7675-11e9-9c89-007bf913036a.png)

**Comment by patmarion** [comment]
You can right click the object and change its color properties in the context menu, or select the object and find its properties in the Properties Panel.  Look at the Color By property.  Do you see the RGB colors listed as an option?  Are the colors per-vertex rgb colors, or is it a textured mesh (with color coming from an image file)?

**Comment by hoangcuongbk80** [comment]
You are right! Thank youuu!!!
