### ISSUE TITLE
bad alignment results 

### ISSUE THREAD

**Issue by hygxy** [RobotLocomotion/LabelFusion#59]
Hey, I was using this tool to create my own data sets. I did everything exactly as README says, but didn't get reasonable results. Here are some pictures from the main window when the interactive marker is on:

![a](https://user-images.githubusercontent.com/28361684/62044995-7f7ca800-b204-11e9-8485-9bf441d58d6c.png)
![b](https://user-images.githubusercontent.com/28361684/62045000-84415c00-b204-11e9-9369-5423e4bcc272.png)
![c](https://user-images.githubusercontent.com/28361684/62045004-87d4e300-b204-11e9-8d2c-1fc774bafd90.png)

The metal part fork is the object to be aligned, in the window it seems that the object and point cloud is coincided, but after "run_create_data -d " i get the following picture :
![0000000001_color_labels](https://user-images.githubusercontent.com/28361684/62045174-fd40b380-b204-11e9-8cac-0e4d25c17f65.png) This is the file "0000000001_color_labels" and "000000000x_color_labels" are even worse.

Any advice would be appreciated!

**Comment by peteflorence** [comment]
Hi there, the issue is most likely due to the calibration of your camera
and/or the quality of the 3D reconstruction. These items are upstream from
the LabelFusion tool. Sorry we don’t have time to help everyone with their
calibration issues, but good luck.

**Comment by hygxy** [comment]
@peteflorence 
Thanks for quick reply. I did use the factory default values for camera intrinsic parameters, I can calibrate the camera manually. But what can I do to improve the quality of 3d reconstruction?

**Comment by peteflorence** [comment]
Improving the calibration will improve the 3D reconstruction. Make sure you
use the new calibration parameters in the 3D reconstruction pipeline,
whether it’s ElasticFusion or whatever you are using.

**Comment by hygxy** [comment]
@peteflorence 
Hello, I've calibrated my camera manually and get better results now. However, I've also observed another frustrating phenomenon: "run_create_data" will create around 600 color images with corresponding labels and poses, some(around 100) of them look good but the rest still presents offsets with different levels and thus can not be applicable. I am wondering if this phenomenon is normal because whatever parameters(even "ideal" parameters I suppose) I set in "renderingtrainingimages.py", there always exists offsets in some images, which are quantitatively more than good ones. 

Another problem is that even if the results are acceptable for one object(e.g, the right one) in the scene, the same parameter sets generate bad results again for others(e.g., the left one).

Today I have a new question: why is in the function "setCameraInstrinsicsAsus()" just one "focalLength" value necessary? I calibrated my camera(it is a realsense), but the results are for resolution 1920x1080, I used [this form](https://stackoverflow.com/questions/39992968/how-to-calculate-field-of-view-of-the-camera-from-camera-intrinsic-matrix) to adjust the intrinsic values to resolution 640x480, during which I assume the field of view doesn't change. Surly I will get different values for fx and fy. So I don't know which one to use in "renderingtrainingimages.py".

I am thankful for any ideas!

**Comment by hygxy** [comment]
I resolved this issue by changing the intrinsic values in MainController.cpp of ElasticFusion and rebuilding it. Thanks again for your advice! @peteflorence

**Comment by Y-pandaman** [comment]
> I resolved this issue by changing the intrinsic values in MainController.cpp of ElasticFusion and rebuilding it. Thanks again for your advice! @peteflorence

hello ,I use the labelfusion in docker, I have changed intrinsic in the function 'setCameraInstrinsicsAsus()',but not changed the intrinsic values in MainController.cpp of ElasticFusion, the results is bad, in the docker ,how I can do?
