### ISSUE TITLE
How to set dimension of the mesh file in my own data?

### ISSUE THREAD

**Issue by hpf9017** [RobotLocomotion/LabelFusion#67]
I add my own data stl file in object-mesh directory,
then modified object_data.yaml.
when in the step "Process into labeled training data"
the run_alignment_tool, gr.launchObjectAlignment(objectName)
it shows my data in the right.

I think because my own data is a bottle, it is too huge,
so I can't get the right ICP result. 

so my question is how to make the pointcloud in the left and the mesh in the right has the same dimension? thank you!
or do your have better solutions? @patmarion

**Comment by hpf9017** [comment]
thanks to @hoangcuongbk80, the unit is meter, so I change the unit in my model from mm to m, which is a stl file, the problem is solved.

**Comment by EulerWong** [comment]
hello, 

> thanks to @hoangcuongbk80, the unit is meter, so I change the unit in my model from mm to m, which is a stl file, the problem is solved.

hello, i meet some problem like this, 

root@cbe969851b41:~/labelfusion/data/logs/2020# run_alignment_tool 
Opening object alignment tool...
log folder: logs/2020
using user specified transform
loading above table pointcloud
showPolyData(colorByName=rgb_colors): array not found
cropping and running ICP
cropping pointcloud to box
computing point to point distance
running ICP
[pcl::VoxelGrid::applyFilter] Leaf size is too small for the input dataset. Integer indices would overflow.ERROR: In /build/vtk-NWL3SN/vtk-5.10.1+dfsg/Hybrid/vtkIterativeClosestPointTransform.cxx, line 270
vtkIterativeClosestPointTransform (0x5b36050): Can't execute with NULL or empty input

ICP finished

did you meet this problem, i do not know how to fix it. i use a .stl mesh file create using AutoCAD.
