### ISSUE TITLE
use self object-mesh, labels not be fit the rgb image

### ISSUE THREAD

**Issue by xiaotmiaomiao** [RobotLocomotion/LabelFusion#68]
Hi,
 I am trying to make object-mesh by myself,  this objcect-mesh made by point cloud, but obj is not good, please tell me object-mesh make method,  like "drill" is so clear and real well?

I use my intel realsense device to collect point cloude data, next using labelfusion make RGB image and labels data(run_create_data -d), but labels not fit the rgb object，why?  

I think the RGB-D camera must be calibration ，but not sure?  Please tell me, your data(LCMLOG) made method?  

We look forward to your reply，thanks！

origin:
![0000000003_rgb](https://user-images.githubusercontent.com/4810898/68575687-8d022900-04a7-11ea-8502-aa6e1cc6055b.png)
labels:
![0000000003_color_labels](https://user-images.githubusercontent.com/4810898/68575578-4dd3d800-04a7-11ea-87f6-98ab2074b077.png)
depth:
![0000000003_depth](https://user-images.githubusercontent.com/4810898/68575588-54fae600-04a7-11ea-8b1f-37aed5e84e08.png)
pose message:
motor:
  label: 14
  num_pixels: 40234.0
  pose: [[-0.3601003011440027, -0.5683465459219573, 1.742092438769996], [0.04408456497025305, -0.05598430907229312, 0.9378419509410567, 0.3396686375339274]]

**Comment by EulerWong** [comment]
hello, how you make your own mesh, i do not know how to make my own mesh, i download mesh from   internet. do you have any idea to make own mesh?

**Comment by benghalensis** [comment]
How was the problem solved?
