### ISSUE TITLE
cannot find xtion2

### ISSUE THREAD

**Issue by MrLuer** [RobotLocomotion/LabelFusion#75]
I tried to run openni2-camera-lcm in the docker，but got those below. xtion2 work fine when run it's own driver

root@a5064dbfa71d:~/labelfusion/data/logs# openni2-camera-lcm
No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni^Z

**Comment by EulerWong** [comment]
hi, MrLuer, did youi fix this issue? i am using xtion2 too, and i meet this problem too, but i do not know how to fix this. if you fixed this, can you help me?
