### ISSUE TITLE
cannot run openni2-camera-lcm 

### ISSUE THREAD

**Issue by MrLuer** [RobotLocomotion/LabelFusion#76]
when I run openni2-camera-lcm got errors below, I run it successfully before and record data from xtion2, but now got errors,I don't know what happen, I tried reboot the docker and host and it not work

root@8ed4a01af538:~# openni2-camera-lcm 
[30B1A1707210441] Depth Camera at /dev/video1 Detected
[30B1A1707210441] Video Camera at /dev/video0 Detected
[30B1A1707210441] Video Camera at /dev/video0 Inited
[30B1A1707210441] Depth Camera at /dev/video1 Inited
Creating IR stream
Creating color stream
Creating Depth stream
v4l2_query_control: error 9, Bad file descriptor
v4l2_query_control: error 9, Bad file descriptor
Depth Stream 0 start
Color Stream 0 start
Received first color image from device
openni2-camera-lcm: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted (core dumped)

**Comment by benghalensis** [comment]
@MrLuer was the problem solved?
How was it solved?
