### ISSUE TITLE
Incompatibility with GeForce RTX 2070 FIXED

### ISSUE THREAD

**Issue by TommasoBendinelli** [RobotLocomotion/LabelFusion#78]
when running run_prep I get the following. I am running with  ianre657:master branch

Running pre-processing stage...
rewind is: 0
error: XDG_RUNTIME_DIR not set in the environment.
calling rewind
LcmLogReader::rewind
timestamp: 1579818510043167
frame: 0
before jpeg read data
imageSize: 69388
about to read jpeg_read_scanlines
finished read jpeg_read_scanlines
finished jpeg_finish_decompress
finished jpeg_destroy_decompress
after jpeg read data
Error: invalid texture reference: /root/ElasticFusion/Core/src/Cuda/convenience.cuh:68
mv: cannot stat 'trimmed_log.lcmlog.posegraph': No such file or directory
sh: 1: cannot open ./trimmed_log.lcmlog.ply: No such file
Traceback (most recent call last):
  File "/root/labelfusion/scripts/prepareForObjectAlignment.py", line 66, in <module>
    with open("./converted_to_ascii.ply") as infile:
IOError: [Errno 2] No such file or directory: './converted_to_ascii.ply'
Done.

I believe that is due to issue with the aforementioned graphic card. In order to make work I think we need to add in /core/src/CMakeLists.txt 75

set(CUDA_ARCH_BIN "30 35 50 52 75" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)").

This however will not compile, as it requires cuda 10. Can I use this repository with cuda 10?

**Comment by TommasoBendinelli** [comment]
I tried using cuda 10 Nvidia/cuda:10.2-devel-ubuntu16.04,  but then run_trim does not work anymore...

**Comment by TommasoBendinelli** [comment]
with Nvidia/cudaopegl it works! If anyone is interested I can share all the procedure

**Comment by mufengjun260** [comment]
@TommasoBendinelli Hey,I have the same problem here with 1660ti,could you please share your procedure with me?Thank you!

**Comment by mufengjun260** [comment]
I solved it by just deleting the line "set(CUDA_ARCH_BIN "30 35 50 52 61" CACHE STRING "Specify 'real' GPU arch to build binaries for, BIN(PTX) format is supported. Example: 1.3 2.1(1.3) or 13 21(13)")",and it works well on 1660ti!
Thank you anyway!

**Comment by ctxqlxs** [comment]
where is the line... @mufengjun260

**Comment by mufengjun260** [comment]
In the CMakeLists of ElasticFusion, which link is https://github.com/mp3guy/ElasticFusion/blob/master/Core/src/CMakeLists.txt

**Comment by ctxqlxs** [comment]
need to rebuild the docker image? @mufengjun260

**Comment by mufengjun260** [comment]
Unfortunately I don’t know that, because I used LabelFusion without Docker.

**Comment by ctxqlxs** [comment]
emm, how to use LabelFusion without Docker? Following [this](https://github.com/RobotLocomotion/LabelFusion/blob/master/docs/setup.rst) ?

**Comment by mufengjun260** [comment]
It seems like this (the last time I used this repo was a year ago, which caused my confused memory), but I encountered a lot of environmental problems in this way, so I think it is best to use the Dockers image provided by the author

**Comment by Liuchongpei** [comment]
@ctxqlxs I solved this problem, you can recompile ElasticFusion in the container after modifying the CMakeLists.txt.

**Comment by Y-pandaman** [comment]
> 使用 Nvidia/cudaopegl 它可以工作！如果有人有兴趣，我可以分享所有程序

hello，I try install labelfusion in 2060 super and 3060 laptop，but  it not work, can you share your docker image?
