### ISSUE TITLE
openni2-camera-lcm  fails to open realsenseD435i camera

### ISSUE THREAD

**Issue by TONG369** [RobotLocomotion/LabelFusion#83]
Hello, excuse me . I am going to use  Label Fusion to make a dataset. However, this progress has not been successfully. I saw that it was written to support realsense serises cameras. But I run this sentence and it goes wrong. I use an Intel realsenseD435I camera. Do you know how to solve this problem? Please tell me in detail, thank you!!! Good luck!!!
@peteflorence @patmarion 

root@71159a6a9dda:~/labelfusion/data/logs/2020-03-31# openni2-camera-lcm
No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni2_driver.cpp @ 761 : Invalid device number 1, there are 0 devices connected.No matching device found.... waiting for devices. Reason: std::__cxx11::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /root/director-build/src/openni2-camera-lcm/src/openni

**Comment by RobbyHuang** [comment]
Hi,@TONG369, I met the same problem. Do you know any information to solve it? Could you tell me in detail ? Thanks!

**Comment by TONG369** [comment]
@RobbyHuang  You need to run roslaunch in the terminal to open the camera, then execute lcm-logger in the terminal，no in the docker.

**Comment by RobbyHuang** [comment]
Thanks,I will have a try.

**Comment by nihar0602** [comment]
Hi @TONG369, @RobbyHuang  
I'm also using a similar approach to you and stuck at the same location as you mentioned in this thread. 
Currently, I have a docker image running for this LabelFusion. 
Below are some doubts: 
are you using ROS outside/without docker? If yes, can you elaborate a little bit, I'm confused with that as I'm new to docker. 
I'm also using IntelRealSense D435i. Can you help me with how you made your dataset using LabelFusion? 

Your help is much appreciated. 
Thank You

**Comment by haijunsu-osu** [comment]
> Thanks,I will have a try.

did you solve the problem?

**Comment by haijunsu-osu** [comment]
> Hi @TONG369, @RobbyHuang
> I'm also using a similar approach to you and stuck at the same location as you mentioned in this thread.
> Currently, I have a docker image running for this LabelFusion.
> Below are some doubts:
> are you using ROS outside/without docker? If yes, can you elaborate a little bit, I'm confused with that as I'm new to docker.
> I'm also using IntelRealSense D435i. Can you help me with how you made your dataset using LabelFusion?
> 
> Your help is much appreciated.
> Thank You

any luck with this issue? I have exactly the same issue.
