### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TONG369** [RobotLocomotion/LabelFusion#85]
Excuse me, my operating system is Ubuntu16.04, cuda8.0,docker19.03,nvidia-docker2.0, and the installation file of the Nvidia driver is installed by .run. When I execute this sentence: run_prep.  I encountered this error, as shown in the following figure:
![QQ图片20200427174116](https://user-images.githubusercontent.com/29472117/80358101-7d886800-88ae-11ea-9b4e-1ea91022664a.png)

When I executed the statement: MESA_GL_VERSION_OVERRIDE = 3.3 run_prep, I encountered this error again, as shown below:

How do you solve this problem? thank you very much!!!
![~5CG7G8GCZG(EPTW9YU0AX9](https://user-images.githubusercontent.com/29472117/80362510-5719fb00-88b5-11ea-9e67-bcfa3422edb6.png)

**Comment by TONG369** [comment]
the problem is solved

**Comment by tom-robo** [comment]
Hello, how did you solve this issue?
