### ISSUE TITLE
i open the GUI but  nothing is displayed

### ISSUE THREAD

**Issue by lzrrr33** [RobotLocomotion/LabelFusion#92]
when i run  `run_alignment_tool`, i get some errors:
`X Error: BadValue (integer parameter out of range for operation) 2
  Extension:    151 (Uknown extension)
  Minor opcode: 3 (Unknown request)
  Resource id:  0x0
X Error: GLXBadContext 158
  Extension:    151 (Uknown extension)
  Minor opcode: 5 (Unknown request)
  Resource id:  0x0
X Error: 0 0
  Extension:    151 (Uknown extension)
  Minor opcode: 26 (Unknown request)
  Resource id:  0x0`
and the  GUI show nothing(as show below)
![2020-07-23 17-32-28 的屏幕截图](https://user-images.githubusercontent.com/49428609/88272442-4db0fb00-cd0b-11ea-910c-44f26e800ffd.png)

any help would be appreciated!

**Comment by lzrrr33** [comment]
Sorry for disturbing you,i have soved this issue

**Comment by anxiaomi** [comment]
how did you solve it?

**Comment by Starslayerx** [comment]
I got the same issue.

**Comment by RiplleYang** [comment]
so, who can leave a solution here
